amp: true
anomaly_clean: false
batch_size: 32
cuda: true
data_type: molecule
epochs: 50
freeze_layers: null
freeze_layers_reversed: false
kfold: 5
learning_rate: 0.0001
load_model_dir: null
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mae
model_name: unimolv1
model_size: 84m
num_classes: 1
patience: 5
remove_hs: true
seed: 42
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 5fold_random
split_seed: 42
target_col_prefix: TARGET
target_cols: TARGET
target_normalize: auto
task: regression
use_amp: true
use_cuda: true
warmup_ratio: 0.03
